[project]
name = "odoo-addons-oca-l10n-france"
version = "17.0.20240119.0"
dependencies = [
    "odoo-addon-l10n_fr_cog>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
